export const Data = [
  {
    _id: '5ae1be0a855f65afc7a3fedf',
    index: 0,
    guid: '8443681d-9188-4504-9b4a-e7a5f9e87adb',
    isActive: false,
    balance: '$3,644.14',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'brown',
    name: 'Emily Vazquez',
    gender: 'female',
    company: 'BLUPLANET',
    email: 'emilyvazquez@bluplanet.com',
    phone: '+1 (993) 423-2284',
    address: '935 Bath Avenue, Foscoe, Northern Mariana Islands, 2215',
    about: 'Est ut officia esse commodo velit nulla incididunt nulla reprehenderit ea. Ex sit nisi veniam reprehenderit esse in irure qui. Velit non sunt occaecat do officia anim elit culpa ullamco officia id fugiat in sunt. Non dolor culpa elit aute aliqua incididunt aute aliqua aliqua fugiat. Consectetur aliqua occaecat officia id sint est aliquip velit reprehenderit consequat ea. Velit labore veniam veniam consectetur magna dolore incididunt reprehenderit consectetur voluptate magna fugiat.\r\n',
    registered: '2018-03-28T12:51:09 -07:00',
    latitude: 82.890375,
    longitude: -164.163936,
    tags: [
      'eiusmod',
      'et',
      'aute',
      'eu',
      'ea',
      'eiusmod',
      'sunt',
    ],
    friends: [
      {
        id: 0,
        name: 'Virginia Petty',
      },
      {
        id: 1,
        name: 'Bender Hull',
      },
      {
        id: 2,
        name: 'Kaufman Blankenship',
      },
    ],
    greeting: 'Hello, Emily Vazquez! You have 1 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5ae1be0a1c8e6b48fd5dad82',
    index: 1,
    guid: 'c798bcee-a8c1-4180-85f9-6c12fca77972',
    isActive: true,
    balance: '$2,898.68',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'green',
    name: 'Melisa Chen',
    gender: 'female',
    company: 'IMAGEFLOW',
    email: 'melisachen@imageflow.com',
    phone: '+1 (957) 578-2934',
    address: '947 Bush Street, Hillsboro, Florida, 4725',
    about: 'Tempor tempor irure voluptate minim qui enim. Aute ullamco elit mollit irure adipisicing duis cupidatat eu mollit non proident laboris quis consequat. Sit ipsum labore elit culpa consectetur officia minim exercitation. Est ipsum commodo id occaecat officia. Laborum ullamco dolore sit minim elit nostrud et fugiat id deserunt est do aliquip sunt. Tempor non ut cupidatat aliqua irure aliquip amet ullamco sint adipisicing ut aliquip.\r\n',
    registered: '2016-05-22T03:10:44 -07:00',
    latitude: 4.865698,
    longitude: 117.264167,
    tags: [
      'aute',
      'ut',
      'sunt',
      'eu',
      'ut',
      'ex',
      'veniam',
    ],
    friends: [
      {
        id: 0,
        name: 'Judy Gates',
      },
      {
        id: 1,
        name: 'Mable Spence',
      },
      {
        id: 2,
        name: 'Lowery Walker',
      },
    ],
    greeting: 'Hello, Melisa Chen! You have 3 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '5ae1be0a4a3260abc3b0377d',
    index: 2,
    guid: '54247089-31c0-4809-ba31-be61f4f3e428',
    isActive: true,
    balance: '$1,150.20',
    picture: 'http://placehold.it/32x32',
    age: 30,
    eyeColor: 'brown',
    name: 'Kirsten Barron',
    gender: 'female',
    company: 'FILODYNE',
    email: 'kirstenbarron@filodyne.com',
    phone: '+1 (921) 563-3336',
    address: '329 Story Court, Mathews, Oklahoma, 6668',
    about: 'Quis eiusmod exercitation aliquip est dolor irure nulla sit ea cupidatat. Duis excepteur irure id id in qui sint pariatur exercitation aliqua commodo. Non qui velit cupidatat aliquip non consectetur esse ut Lorem exercitation fugiat est aute ea. Fugiat commodo exercitation nisi officia sint cillum aliqua ad. Anim cupidatat ex consectetur et commodo enim velit cillum enim non ut veniam id. Occaecat Lorem aliqua fugiat cillum esse do.\r\n',
    registered: '2015-07-18T06:39:38 -07:00',
    latitude: 83.597162,
    longitude: 1.956353,
    tags: [
      'anim',
      'culpa',
      'et',
      'quis',
      'nostrud',
      'esse',
      'enim',
    ],
    friends: [
      {
        id: 0,
        name: 'Eliza Lyons',
      },
      {
        id: 1,
        name: 'Alice Schroeder',
      },
      {
        id: 2,
        name: 'Nixon Calderon',
      },
    ],
    greeting: 'Hello, Kirsten Barron! You have 4 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5ae1be0ac7317db7e4537d92',
    index: 3,
    guid: 'f3f0f476-d3d8-45dd-9bf5-c9addb6624cb',
    isActive: false,
    balance: '$1,017.75',
    picture: 'http://placehold.it/32x32',
    age: 25,
    eyeColor: 'green',
    name: 'Lynn Knox',
    gender: 'male',
    company: 'SPRINGBEE',
    email: 'lynnknox@springbee.com',
    phone: '+1 (995) 488-3702',
    address: '851 Stryker Street, Soudan, Minnesota, 5809',
    about: 'Sint dolore amet irure ex. Laboris cillum ullamco exercitation amet elit eu ad laboris eu consectetur irure ipsum minim exercitation. Aliquip occaecat sint officia non nostrud nostrud deserunt magna quis exercitation velit pariatur reprehenderit. Anim non qui labore Lorem duis commodo nostrud do adipisicing dolore consequat in amet.\r\n',
    registered: '2016-03-15T01:37:31 -07:00',
    latitude: -15.09219,
    longitude: -21.779859,
    tags: [
      'aliqua',
      'tempor',
      'irure',
      'fugiat',
      'sunt',
      'velit',
      'occaecat',
    ],
    friends: [
      {
        id: 0,
        name: 'Latonya Henry',
      },
      {
        id: 1,
        name: 'Berg Woodard',
      },
      {
        id: 2,
        name: 'Margo Small',
      },
    ],
    greeting: 'Hello, Lynn Knox! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5ae1be0a231026c98981a1a1',
    index: 4,
    guid: 'b5d4da5b-635f-4c6a-a569-1caae91ee0af',
    isActive: true,
    balance: '$2,100.23',
    picture: 'http://placehold.it/32x32',
    age: 32,
    eyeColor: 'brown',
    name: 'Marla Cunningham',
    gender: 'female',
    company: 'MUSANPOLY',
    email: 'marlacunningham@musanpoly.com',
    phone: '+1 (984) 425-2187',
    address: '281 Provost Street, Summerset, New Jersey, 7105',
    about: 'Mollit quis et ipsum sit dolor ea. Anim consequat culpa tempor non veniam non culpa est commodo ex id voluptate eu. Ullamco proident aute ex consectetur amet officia cillum ullamco velit enim quis. Do deserunt in aliqua ut eiusmod quis in in voluptate aliqua ad nostrud proident. Cupidatat ex velit et cillum minim officia irure magna ea quis.\r\n',
    registered: '2015-07-25T07:58:54 -07:00',
    latitude: 38.663794,
    longitude: -136.677059,
    tags: [
      'ipsum',
      'incididunt',
      'consectetur',
      'quis',
      'adipisicing',
      'dolore',
      'officia',
    ],
    friends: [
      {
        id: 0,
        name: 'Lorna Zimmerman',
      },
      {
        id: 1,
        name: 'Gray Donovan',
      },
      {
        id: 2,
        name: 'Gayle White',
      },
    ],
    greeting: 'Hello, Marla Cunningham! You have 9 unread messages.',
    favoriteFruit: 'apple',
  },
]